### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by bfontaine** [fabYkun/corrortho#1]
Bonjour, sous quelle [licence](https://github.com/blog/1530-choosing-an-open-source-license) le code est-il publié ?

**Comment by fabYkun** [comment]
Sous licence "pas de licence" vous pouvez faire ce que vous voulez avec il
n'y a pas de soucis.

2017-04-19 8:31 GMT-04:00 Baptiste Fontaine <notifications@github.com>:

**Comment by bfontaine** [comment]
Sans licence, c’est un code propriétaire et on ne peut pas faire ce qu’on veut ;)

**Comment by fabYkun** [comment]
Oui bien sûr et merci d'avoir demandé c'était juste pour dire qu'à l'époque
je n'y avais pas prêté d'attention ^^

2017-04-19 15:57 GMT-04:00 Baptiste Fontaine <notifications@github.com>:
